version: "3.3"

volumes: 
    sdg_recognize_volume:

services: 
    web:
        image: jlrbawe/sdg_recognizer_image
        restart: always
        environment:
            - TZ=Europe/Berlin
        ports: 
            - 8080:8080

